name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev googletest

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=ON
          make
      
      - name: run tests
        run: ./bin/tests